apiVersion: apps/v1
kind: Deployment
metadata:
  name: earscopeweb-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earscopeweb-backend
  template:
    metadata:
      labels:
        app: earscopeweb-backend
    spec:
      containers:
        - name: earscopeweb-backend
          image: adrfstwn/earscopeweb-backend:latest
          volumeMounts:
            - name: earscopeweb-backend-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: earscopeweb-backend-volume
          secret:
            secretName: earscopeweb-backend-secret
            items:
              - key: earscopeweb-backend-secret
                path: .env
            
          # envFrom:
          #   - secretRef:
          #       name: earscopeweb-backend-secret

