apiVersion: apps/v1
kind: Deployment
metadata:
  name: earscopeweb-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earscopeweb-backend
  template:
    metadata:
      labels:
        app: earscopeweb-backend
    spec:
      containers:
        - name: earscopeweb-backend
          image: adrfstwn/earscopeweb-backend:latest
          envFrom:
            - secretRef:
                name: earscopeweb-backend-secret

