apiVersion: apps/v1
kind: Deployment
metadata:
  name: earscope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earscope
  template:
    metadata:
      labels:
        app: earscope
    spec:
      containers:
      - name: earscope
        image: earscope:latest
        ports:
        - containerPort: 8092