apiVersion: apps/v1
kind: Deployment
metadata:
  name: earscope-model
  labels:
    app: earscope-model
spec:
  selector:
    matchLabels:
      app: earscope-model
  template:
    metadata:
      labels:
        app: earscope-model
    spec:
      containers:
        - name: earscope-model
          image: 103.155.246.50/earscope-model:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
