apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/deployment-backend.yaml
  - backend/service-backend.yaml
  - frontend/deployment-frontend.yaml
  - frontend/service-frontend.yaml
