apiVersion: v1
kind: Service
metadata:
  name: earscopeweb-backend
spec:
  selector:
    app: earscopeweb-backend
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8081
  type: ClusterIP