apiVersion: apps/v1
kind: Deployment
metadata:
  name: earscopeweb-frontend
  labels:
    app: earscopeweb-frontend
spec:
  selector:
    matchLabels:
      app: earscopeweb-frontend
  template:
    metadata:
      labels:
        app: earscopeweb-frontend
    spec:
      containers:
        - name: earscopeweb-frontend
          image: adrfstwn/earscopeweb-frontend:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent