apiVersion: v1
kind: Service
metadata:
  name: earscopeweb-frontend
spec:
  selector:
    app: earscopeweb-frontend
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8080
  type: ClusterIP

