apiVersion: apps/v1
kind: Deployment
metadata:
  name: earscope-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earscope-model
  template:
    metadata:
      labels:
        app: earscope-model
    spec:
      containers:
        - name: earscope-model
          image: adrfstwn/earscope-model:latest # 1742675401
          env:
          - name: FLASK_APP
            value: "run.py"
          - name: FLASK_DEBUG
            value: "1"
          - name: FLASK_ENV
            value: "development"
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: earscope-secret
                key: APP_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: earscope-secret
                key: DATABASE_URL
          - name: API_SEND_VIDEO_URL
            valueFrom:
              secretKeyRef:
                name: earscope-secret
                key: API_SEND_VIDEO_URL
